### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by larsw** [cultureamp/kestrel#54]
What kind of license is this project published under?

**Comment by milgner** [comment]
Any updates on this? I'm thinking about using Kestrel in an application (great API & functionality!) - but without an official license declaration that's not an option unfortunately.

**Comment by milgner** [comment]
Never mind: I just saw that the [build configuration mentions Apache 2.0 as the license](https://github.com/cultureamp/kestrel/blob/a3bd9e74880027573ba24ad0b745b4b5b05bcc58/build.gradle#L85)! :tada: 
So I guess this can be closed...
